import { User } from '~/auth/domain/entities/user.entity'
import type { IUserRepository } from '~/auth/domain/repositories/user.repository'
import type { Email } from '~/auth/domain/value-objects/email.vo'
import type { Password } from '~/auth/domain/value-objects/password.vo'

export class AuthService {
  constructor(private readonly userRepository: IUserRepository) {}

  async register(email: Email, password: Password): Promise<User> {
    // Hashing logic will be added here
    const newUser = new User(
      // ID will be generated by the database
      '',
      email,
      password
    )
    return this.userRepository.create(newUser)
  }
}
